# Generated by Django 5.2.16 on 2026-07-12 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=100)),
                ('source_url', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_sources',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi', models.CharField(max_length=10, unique=True)),
                ('entity_type_code', models.CharField(max_length=1)),
                ('provider_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_credential', models.CharField(blank=True, max_length=50, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('enumeration_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'providers',
                'indexes': [models.Index(fields=['provider_first_name'], name='idx_prov_first_name'), models.Index(fields=['provider_last_name'], name='idx_prov_last_name')],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('taxonomy_description', models.CharField(max_length=255)),
                ('grouping', models.CharField(blank=True, max_length=255, null=True)),
                ('classification', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('source_version', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'taxonomy_codes',
                'indexes': [models.Index(fields=['taxonomy_description'], name='idx_tax_desc')],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('source_version', models.CharField(blank=True, max_length=100, null=True)),
                ('import_started_at', models.DateTimeField()),
                ('import_completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('data_source', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='providers.datasource')),
            ],
            options={
                'db_table': 'import_batches',
                'indexes': [models.Index(fields=['data_source'], name='idx_imp_source')],
            },
        ),
        migrations.CreateModel(
            name='ProviderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(max_length=50)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='providers.provider')),
            ],
            options={
                'db_table': 'provider_addresses',
                'indexes': [models.Index(fields=['provider'], name='idx_addr_provider'), models.Index(fields=['city'], name='idx_addr_city'), models.Index(fields=['state'], name='idx_addr_state'), models.Index(fields=['zip_code'], name='idx_addr_zip_code')],
            },
        ),
        migrations.CreateModel(
            name='ProviderTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('license_state', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='provider_taxonomies', to='providers.provider')),
                ('taxonomy_code', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='provider_taxonomies', to='providers.taxonomycode')),
            ],
            options={
                'db_table': 'provider_taxonomies',
                'indexes': [models.Index(fields=['provider'], name='idx_pt_provider'), models.Index(fields=['taxonomy_code'], name='idx_pt_taxonomy')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'taxonomy_code', 'license_number', 'license_state'), name='uq_provider_taxonomy_license')],
            },
        ),
    ]
